title: Research Software Engineers International
#author: IntRSE
#email: info@nl-rse.org
description: > # this means to ignore newlines until "baseurl:"
  The website of the international RSE community
#twitter_username: nl_rse
github_username:  RSE-leaders

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - blog.md
  - 2020-workshop.md
  - assoc.md
  - contact.md
# - code-of-conduct.md
# - communication.md

# Build settings
markdown: kramdown
theme: minima

cc-by: >-
  ![Badge for the Creative Commons BY license](/img/cc-by.png)  
    
  Unless otherwise noted, the content of this website is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by/4.0/).

plugins:
 - jekyll-feed
 - jekyll-seo-tag